# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trust_engine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'trust_engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12trust_engine.proto\x12\x0f\x61vaira.trust.v1\"W\n\x0cRiskEnvelope\x12\x15\n\rmax_spend_usd\x18\x01 \x01(\x01\x12\x17\n\x0f\x61llowed_actions\x18\x02 \x03(\t\x12\x17\n\x0f\x62locked_actions\x18\x03 \x03(\t\"M\n\x06Intent\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\x12\x11\n\tvalue_usd\x18\x03 \x01(\x01\x12\x10\n\x08\x61gent_id\x18\x04 \x01(\t\"q\n\x15ValidateIntentRequest\x12\'\n\x06intent\x18\x01 \x01(\x0b\x32\x17.avaira.trust.v1.Intent\x12/\n\x08\x65nvelope\x18\x02 \x01(\x0b\x32\x1d.avaira.trust.v1.RiskEnvelope\">\n\x16ValidateIntentResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"N\n\x10LogIntentRequest\x12\'\n\x06intent\x18\x01 \x01(\x0b\x32\x17.avaira.trust.v1.Intent\x12\x11\n\tprev_hash\x18\x02 \x01(\t\"=\n\x11LogIntentResponse\x12\x13\n\x0bintent_hash\x18\x01 \x01(\t\x12\x13\n\x0bmerkle_root\x18\x02 \x01(\t\")\n\x15GetAvairaScoreRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"6\n\x16GetAvairaScoreResponse\x12\r\n\x05score\x18\x01 \x01(\x01\x12\r\n\x05grade\x18\x02 \x01(\t2\xa7\x02\n\x0bTrustEngine\x12\x61\n\x0eValidateIntent\x12&.avaira.trust.v1.ValidateIntentRequest\x1a\'.avaira.trust.v1.ValidateIntentResponse\x12R\n\tLogIntent\x12!.avaira.trust.v1.LogIntentRequest\x1a\".avaira.trust.v1.LogIntentResponse\x12\x61\n\x0eGetAvairaScore\x12&.avaira.trust.v1.GetAvairaScoreRequest\x1a\'.avaira.trust.v1.GetAvairaScoreResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trust_engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RISKENVELOPE']._serialized_start=39
  _globals['_RISKENVELOPE']._serialized_end=126
  _globals['_INTENT']._serialized_start=128
  _globals['_INTENT']._serialized_end=205
  _globals['_VALIDATEINTENTREQUEST']._serialized_start=207
  _globals['_VALIDATEINTENTREQUEST']._serialized_end=320
  _globals['_VALIDATEINTENTRESPONSE']._serialized_start=322
  _globals['_VALIDATEINTENTRESPONSE']._serialized_end=384
  _globals['_LOGINTENTREQUEST']._serialized_start=386
  _globals['_LOGINTENTREQUEST']._serialized_end=464
  _globals['_LOGINTENTRESPONSE']._serialized_start=466
  _globals['_LOGINTENTRESPONSE']._serialized_end=527
  _globals['_GETAVAIRASCOREREQUEST']._serialized_start=529
  _globals['_GETAVAIRASCOREREQUEST']._serialized_end=570
  _globals['_GETAVAIRASCORERESPONSE']._serialized_start=572
  _globals['_GETAVAIRASCORERESPONSE']._serialized_end=626
  _globals['_TRUSTENGINE']._serialized_start=629
  _globals['_TRUSTENGINE']._serialized_end=924
# @@protoc_insertion_point(module_scope)
