# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import trust_engine_pb2 as trust__engine__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in trust_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrustEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateIntent = channel.unary_unary(
                '/avaira.trust.v1.TrustEngine/ValidateIntent',
                request_serializer=trust__engine__pb2.ValidateIntentRequest.SerializeToString,
                response_deserializer=trust__engine__pb2.ValidateIntentResponse.FromString,
                _registered_method=True)
        self.LogIntent = channel.unary_unary(
                '/avaira.trust.v1.TrustEngine/LogIntent',
                request_serializer=trust__engine__pb2.LogIntentRequest.SerializeToString,
                response_deserializer=trust__engine__pb2.LogIntentResponse.FromString,
                _registered_method=True)
        self.GetAvairaScore = channel.unary_unary(
                '/avaira.trust.v1.TrustEngine/GetAvairaScore',
                request_serializer=trust__engine__pb2.GetAvairaScoreRequest.SerializeToString,
                response_deserializer=trust__engine__pb2.GetAvairaScoreResponse.FromString,
                _registered_method=True)


class TrustEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ValidateIntent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogIntent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvairaScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrustEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateIntent,
                    request_deserializer=trust__engine__pb2.ValidateIntentRequest.FromString,
                    response_serializer=trust__engine__pb2.ValidateIntentResponse.SerializeToString,
            ),
            'LogIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.LogIntent,
                    request_deserializer=trust__engine__pb2.LogIntentRequest.FromString,
                    response_serializer=trust__engine__pb2.LogIntentResponse.SerializeToString,
            ),
            'GetAvairaScore': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvairaScore,
                    request_deserializer=trust__engine__pb2.GetAvairaScoreRequest.FromString,
                    response_serializer=trust__engine__pb2.GetAvairaScoreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'avaira.trust.v1.TrustEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('avaira.trust.v1.TrustEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrustEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ValidateIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avaira.trust.v1.TrustEngine/ValidateIntent',
            trust__engine__pb2.ValidateIntentRequest.SerializeToString,
            trust__engine__pb2.ValidateIntentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LogIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avaira.trust.v1.TrustEngine/LogIntent',
            trust__engine__pb2.LogIntentRequest.SerializeToString,
            trust__engine__pb2.LogIntentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvairaScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avaira.trust.v1.TrustEngine/GetAvairaScore',
            trust__engine__pb2.GetAvairaScoreRequest.SerializeToString,
            trust__engine__pb2.GetAvairaScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
